# Generated by Django 6.0.5 on 2026-05-19 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the restaurant.', max_length=255)),
                ('description', models.TextField(help_text='A short description about the restaurant, cuisine, or ambiance.')),
                ('address', models.CharField(help_text='Physical address of the restaurant.', max_length=500)),
                ('rating', models.IntegerField(help_text='Customer rating between 1 (poor) and 5 (excellent).', validators=[django.core.validators.MinValueValidator(1, message='Rating must be at least 1.'), django.core.validators.MaxValueValidator(5, message='Rating cannot exceed 5.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'ordering': ['-created_at'],
            },
        ),
    ]
